services:
  knsewa-web-dev:
    build: .
    container_name: knsewa-web-dev
    restart: unless-stopped
    networks:
      - hosting
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.knsewa-web-dev.rule=Host(`knsewa-dev.zunkireelabs.com`)"
      - "traefik.http.routers.knsewa-web-dev.entrypoints=websecure"
      - "traefik.http.routers.knsewa-web-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.knsewa-web-dev.loadbalancer.server.port=80"

networks:
  hosting:
    external: true
