services:
  knsewa-web-prod:
    build: .
    container_name: knsewa-web-prod
    restart: unless-stopped
    networks:
      - hosting
    labels:
      - "traefik.enable=true"
      # Router
      - "traefik.http.routers.knsewa-web-prod.rule=Host(`knsewa.com`) || Host(`www.knsewa.com`)"
      - "traefik.http.routers.knsewa-web-prod.entrypoints=websecure"
      - "traefik.http.routers.knsewa-web-prod.tls.certresolver=letsencrypt"
      # Service
      - "traefik.http.services.knsewa-web-prod.loadbalancer.server.port=80"

networks:
  hosting:
    external: true
