import type { ProjectsPageContent } from '@/types/content';

export const projectsPageContent: ProjectsPageContent = {
  seo: {
    title: 'Our Projects | Khushbu Nirman Sewa Pvt Ltd',
    description:
      'Explore 500+ construction projects by Khushbu Nirman Sewa across Nepal — buildings, roads, bridges, hospitals, water supply, and energy infrastructure in all 7 provinces.',
    keywords: [
      'knsewa projects',
      'construction projects nepal',
      'building projects biratnagar',
      'infrastructure nepal',
      'government projects nepal',
    ],
  },

  hero: {
    label: 'OUR PROJECTS',
    headline: 'Building What Matters',
    description:
      'From hospitals and schools to bridges and water treatment plants — explore our portfolio of projects transforming communities across Nepal.',
    backgroundImage: '/images/banners/about-banner.jpg',
    breadcrumbs: [
      { label: 'Home', href: '/' },
      { label: 'Projects' },
    ],
  },

  stats: [
    { value: '500', label: 'Projects Completed', suffix: '+' },
    { value: '24', label: 'Active Sectors', suffix: '' },
    { value: '7', label: 'Provinces Covered', suffix: '' },
    { value: '30', label: 'Years of Delivery', suffix: '+' },
  ],

  categories: [
    'All',
    'Government',
    'Infrastructure',
    'Healthcare',
    'Educational',
    'Commercial',
  ],

  projects: [
    {
      id: 'project-1',
      slug: 'deerwalk-complex-kathmandu',
      title: 'Basement + G + 4 Building at Deerwalk Complex',
      category: 'Educational',
      clientType: 'commercial',
      client: 'Deerwalk Group Limited',
      description:
        'RCC Frame Structure (7 Storey) with Double Basement including Brick Masonry, Plaster, Electrical, Sanitary, Landscaping, HVAC, Lift Machine Fixing, Structural Steel Work.',
      location: 'Sifal, Kathmandu',
      scope: 'New Construction',
      status: 'running',
      year: '2022',
      highlights: [
        '7-storey RCC frame structure',
        'Double basement',
        'HVAC & lift installation',
        'Full landscaping',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-1/p1-6-small.jpg',
        featured: '/images/project-galleries/project-1/Deerwalk-img1.jpg',
        gallery: [
          '/images/project-galleries/project-1/6.jpg',
          '/images/project-galleries/project-1/3.jpg',
          '/images/project-galleries/project-1/4.jpg',
          '/images/project-galleries/project-1/2.jpg',
          '/images/project-galleries/project-1/5.jpg',
          '/images/project-galleries/project-1/7.jpg',
          '/images/project-galleries/project-1/8.jpg',
          '/images/project-galleries/project-1/9.jpg',
        ],
      },
      seo: {
        title: 'Deerwalk Complex Building | KNSEWA Projects',
        description: '7-storey educational building with double basement at Deerwalk Complex, Sifal, Kathmandu.',
      },
    },
    {
      id: 'project-2',
      slug: 'baikunthe-drinking-water-madi',
      title: 'Baikunthe Underground Drinking Water Project',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Madi Integrated Inclusive Sustainable Development Project',
      description:
        'Over Head Tank (OHT) Construction, Pipe laying & jointing of different sizes along with household connection around the Baikunthe Underground Drinking Water Project.',
      location: 'Madi, Chitwan',
      scope: 'Water Supply',
      status: 'running',
      year: '2022',
      highlights: [
        'Overhead tank construction',
        'Pipe laying & jointing',
        'Household connections',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-2/p2-small.jpg',
        featured: '/images/project-galleries/project-2/1.jpg',
        gallery: [
          '/images/project-galleries/project-2/1.jpg',
          '/images/project-galleries/project-2/3.jpg',
        ],
      },
      seo: {
        title: 'Baikunthe Water Project | KNSEWA Projects',
        description: 'Underground drinking water supply project in Madi, Chitwan.',
      },
    },
    {
      id: 'project-3',
      slug: 'sewerage-treatment-letang',
      title: 'Sewerage and Treatment Plant in Letang',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Federal Water Supply & Sewerage Management Project, Biratnagar',
      description:
        'Treatment Plant (2 No), Pipe laying & jointing, Sewer Line Works with Chamber, 2 Storey RCC Building, Guard House, Compound Wall, Landscaping, Settling Tank, Approach Channel, Bar Screening, Oil & Grease Separator, Grit Pit, Drying Bed & Reed Bed.',
      location: 'Letang, Morang',
      scope: 'Water Treatment',
      status: 'running',
      year: '2019',
      highlights: [
        '2 treatment plants',
        'Complete sewer line system',
        '2-storey RCC building',
        'Deep tube well',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-3/p-3-small.jpg',
        featured: '/images/project-galleries/project-3/6.jpg',
        gallery: [
          '/images/project-galleries/project-3/6.jpg',
          '/images/project-galleries/project-3/img-1.jpg',
        ],
      },
      seo: {
        title: 'Sewerage Treatment Plant Letang | KNSEWA Projects',
        description: 'Sewerage and treatment plant construction in Letang, Morang.',
      },
    },
    {
      id: 'project-4',
      slug: 'pathari-municipal-hospital',
      title: '15 Bedded Pathari Sanischare Municipal Hospital',
      category: 'Healthcare',
      clientType: 'government',
      client: 'Pathari Sanischare Municipality, Morang',
      description:
        'RCC Frame Structure (2 Storey) Building with RAMP Provision for all floors including Brick Masonry, Plaster, Electrical, Sanitary, Landscaping, HVAC, Lift Machine Fixing, Structural Steel Work. Includes Guard House and Mortuary Block.',
      location: 'Pathari, Morang',
      scope: 'New Construction',
      status: 'running',
      year: '2021',
      highlights: [
        '15-bed hospital facility',
        '2-storey RCC with ramp access',
        'HVAC & lift systems',
        'Guard house & mortuary',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-4/p-4-small.jpg',
        featured: '/images/project-galleries/project-4/1.jpg',
        gallery: [
          '/images/project-galleries/project-4/1.jpg',
          '/images/project-galleries/project-4/2.jpg',
        ],
      },
      seo: {
        title: 'Pathari Municipal Hospital | KNSEWA Projects',
        description: '15-bed municipal hospital in Pathari, Morang.',
      },
    },
    {
      id: 'project-5',
      slug: 'pathari-khola-bridge',
      title: 'Buddha Marga ko Pathari Khola ma Pul (Bridge)',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Pathari Sanischare Municipality, Morang',
      description:
        'Double Lane 40m Long Prestressed Concrete (PSC) T Beam Bridge, Cast-in-situ RCC Pile of 800mm diameter (32 No x 16m) = 512 Rm, River Training and Protection Works, Wing Wall and Approach Road.',
      location: 'Pathari, Ward No-6, Morang',
      scope: 'Bridge Construction',
      status: 'running',
      year: '2022',
      highlights: [
        '40m prestressed concrete bridge',
        '32 RCC piles (800mm)',
        'River training works',
        'Approach road construction',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-5/p5-small.jpg',
        featured: '/images/project-galleries/project-5/1.jpg',
        gallery: [
          '/images/project-galleries/project-5/1.jpg',
          '/images/project-galleries/project-5/2.jpg',
        ],
      },
      seo: {
        title: 'Pathari Khola Bridge | KNSEWA Projects',
        description: '40m prestressed concrete bridge at Pathari, Morang.',
      },
    },
    {
      id: 'project-6',
      slug: 'jahada-municipal-hospital',
      title: '15 Bedded Municipal Hospital at Jahada',
      category: 'Healthcare',
      clientType: 'government',
      client: 'Jahada Rural Municipality, Morang',
      description:
        'RCC Frame Structure (3 Storey) Building, 800mm thickness Raft/Mat Foundation and RAMP Provision for all floors including Brick Masonry, Plaster, Electrical, Sanitary, Landscaping, HVAC, Lift and Structural Steel Work. Includes Guard House and Mortuary Block.',
      location: 'Majhare, Morang',
      scope: 'New Construction',
      status: 'running',
      completionPercentage: 90,
      contractValue: 'NPR 149.7M',
      year: '2022',
      highlights: [
        '15-bed hospital',
        '3-storey RCC structure',
        'Raft foundation (800mm)',
        'Full ramp accessibility',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-6/p-6-small.jpg',
        featured: '/images/project-galleries/project-6/1.jpg',
        gallery: [
          '/images/project-galleries/project-6/1.jpg',
          '/images/project-galleries/project-6/2.jpg',
          '/images/project-galleries/project-6/3.jpg',
        ],
      },
      seo: {
        title: 'Jahada Municipal Hospital | KNSEWA Projects',
        description: '15-bed municipal hospital at Jahada, Morang.',
      },
    },
    {
      id: 'project-7',
      slug: 'jahada-administration-building',
      title: 'Administration Building at Jahada-5',
      category: 'Government',
      clientType: 'government',
      client: 'Jahada Rural Municipality, Morang',
      description:
        'RCC Frame Structure Building including Brick Masonry, Plaster, Electrical, Sanitary, Landscaping, HVAC. Also includes Guard House, Canteen Block, Generator Shed, Vehicle Parking Shed and Boundary Wall of 250m.',
      location: 'Jahada-5, Majhare, Morang',
      scope: 'New Construction',
      status: 'running',
      year: '2022',
      highlights: [
        'Full administration complex',
        'Guard house & canteen',
        '250m boundary wall',
        'Generator & parking sheds',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-7/p-7-small.jpg',
        featured: '/images/project-galleries/project-7/1.jpg',
        gallery: [
          '/images/project-galleries/project-7/1.jpg',
          '/images/project-galleries/project-7/3.jpg',
          '/images/project-galleries/project-7/4.jpg',
          '/images/project-galleries/project-7/5.jpg',
        ],
      },
      seo: {
        title: 'Jahada Administration Building | KNSEWA Projects',
        description: 'Administration building complex at Jahada-5, Morang.',
      },
    },
    {
      id: 'project-8',
      slug: 'pm-park-biratnagar',
      title: 'Prime Minister Park at Biratnagar',
      category: 'Government',
      clientType: 'government',
      client: 'Biratnagar Metropolitan City',
      description:
        'Boundary Wall, Decorative Boundary Wall, Drainage, Main Entrance Gate, Foot Deck, Foot Over Bridge, Monument Area, Open Air Theater, Pedestrian Open Statue Museum, PM Statue, Swimming Pool, Gazebo, GYM Centre, Landscaping and Beautification.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'running',
      completionPercentage: 85,
      contractValue: 'NPR 150.6M',
      year: '2022',
      highlights: [
        'Open air theater',
        'Swimming pool & gym',
        'Statue museum',
        'Complete landscaping',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-8/1.jpg',
        featured: '/images/project-galleries/project-8/1.jpg',
        gallery: [
          '/images/project-galleries/project-8/1.jpg',
        ],
      },
      seo: {
        title: 'PM Park Biratnagar | KNSEWA Projects',
        description: 'Prime Minister Park construction at Biratnagar, Morang.',
      },
    },
    {
      id: 'project-9',
      slug: 'patan-secondary-school',
      title: 'Patan Secondary School',
      category: 'Educational',
      clientType: 'government',
      client: 'Central Level Project Implementation Unit, Kathmandu',
      description:
        'RCC Frame Structure (4 Storey) with Raft Foundation 0.5m thickness, area 1115.93 Sqm. Retrofitting of Nepal\'s Second Oldest School. Plinth Area: 1138.60 Sqm, Built-Up Area: 3409.60 Sqm.',
      location: 'Patandhoka, Lalitpur',
      scope: 'Renovation & Retrofitting',
      status: 'completed',
      year: '2021',
      highlights: [
        'Nepal\'s 2nd oldest school',
        '4-storey retrofitting',
        '3,409 sqm built-up area',
        'PM recognition award',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-9/top-view-small.jpg',
        featured: '/images/project-galleries/project-9/top-view.jpg',
        gallery: [
          '/images/project-galleries/project-9/top-view.jpg',
          '/images/project-galleries/project-9/patan-school-3.jpg',
          '/images/project-galleries/project-9/patan-school-6.jpg',
          '/images/awards/patan-token-distribution.jpg',
        ],
      },
      seo: {
        title: 'Patan Secondary School | KNSEWA Projects',
        description: 'Retrofitting of Patan Secondary School in Lalitpur — Nepal\'s 2nd oldest school.',
      },
    },
    {
      id: 'project-10',
      slug: 'panchkhal-sez-admin-building',
      title: 'Administrative Building at Panchkhal SEZ',
      category: 'Government',
      clientType: 'government',
      client: 'Special Economic Zone Authority, Kathmandu',
      description:
        'RCC Frame Structure, 1578 Sqm area including Brick Masonry, Plaster, Electrical, Sanitary, Landscaping, Structural Steel Work. Plinth Area: 1578 Sqm, Built-Up Area: 5256 Sqm.',
      location: 'Panchkhal, Kavrepalanchowk',
      scope: 'New Construction',
      status: 'completed',
      year: '2021',
      highlights: [
        '5,256 sqm built-up area',
        'Special Economic Zone',
        'Full MEP systems',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-10/p-10-small.jpg',
        featured: '/images/project-galleries/project-10/P3.jpg',
        gallery: [
          '/images/project-galleries/project-10/P3.jpg',
          '/images/project-galleries/project-10/P1.jpg',
          '/images/project-galleries/project-10/P2.jpg',
          '/images/project-galleries/project-10/240739276.jpg',
          '/images/project-galleries/project-10/241164731.jpg',
        ],
      },
      seo: {
        title: 'Panchkhal SEZ Admin Building | KNSEWA Projects',
        description: 'Administrative building and land development at Panchkhal Special Economic Zone.',
      },
    },
    {
      id: 'project-12',
      slug: 'mangadh-water-supply',
      title: 'Mangadh Sahalagani Water Supply and Sanitation',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Water Supply & Sanitation Division Office, Biratnagar',
      description:
        '255 Cum Capacity RCC Overhead Tank, 200 Cum Ground Reservoirs (2 No), 144 Cum/Hr Water Treatment Plants (3 No), Deep Tube Wells (5 No, 625m total), Submersible Pumps, Pressure Aerator Towers, Iron Removal Filters, Transformers.',
      location: 'Biratnagar, Morang',
      scope: 'Water Supply',
      status: 'completed',
      year: '2018',
      highlights: [
        '255 cum overhead tank',
        '3 water treatment plants',
        '5 deep tube wells',
        'Complete pumping system',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-12/p-12-small.jpg',
        featured: '/images/project-galleries/project-12/1.jpg',
        gallery: [
          '/images/project-galleries/project-12/1.jpg',
          '/images/project-galleries/project-12/2.jpg',
          '/images/project-galleries/project-12/3.jpg',
          '/images/project-galleries/project-12/4.jpg',
        ],
      },
      seo: {
        title: 'Mangadh Water Supply | KNSEWA Projects',
        description: 'Large-scale water supply and sanitation project in Biratnagar, Morang.',
      },
    },
    {
      id: 'project-13',
      slug: 'kiratichowk-birendranagar-road',
      title: 'Kiratichowk Birendranagar Road',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Infrastructure Development Office, Biratnagar',
      description:
        '8.75 Km of Asphalt Concrete Road, RCC Drain on both sides, Protection & Cross Drainage Works, Traffic Control, Management and Safety Works, Bio-engineering Works.',
      location: 'Pathari Sanischare Municipality, Morang',
      scope: 'Road Construction',
      status: 'completed',
      year: '2022',
      highlights: [
        '8.75 km asphalt road',
        'RCC drains both sides',
        'Cross drainage works',
        'Bio-engineering',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-13/p-13-small.jpg',
        featured: '/images/project-galleries/project-13/1.jpg',
        gallery: [
          '/images/project-galleries/project-13/1.jpg',
          '/images/project-galleries/project-13/2.jpg',
          '/images/project-galleries/project-13/3.jpg',
          '/images/project-galleries/project-13/4.jpg',
        ],
      },
      seo: {
        title: 'Kiratichowk Road | KNSEWA Projects',
        description: '8.75 km asphalt road construction in Pathari Sanischare Municipality.',
      },
    },
    {
      id: 'project-14',
      slug: 'stormwater-drain-biratnagar',
      title: 'Stormwater Concrete Drain',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Biratnagar Metropolitan City',
      description:
        '1745m Long RCC Drain with RCC Cover Slab along with 2 No of Syphon.',
      location: 'Biratnagar, Morang',
      scope: 'Drainage',
      status: 'completed',
      year: '2022',
      highlights: [
        '1,745m long RCC drain',
        'RCC cover slab',
        '2 syphons',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-14/p-14-small.jpg',
        featured: '/images/project-galleries/project-14/2.jpg',
        gallery: [
          '/images/project-galleries/project-14/1.jpg',
          '/images/project-galleries/project-14/2.jpg',
        ],
      },
      seo: {
        title: 'Stormwater Drain | KNSEWA Projects',
        description: '1745m stormwater drainage system in Biratnagar.',
      },
    },
    {
      id: 'project-16',
      slug: 'gorkhapatra-sansthan-building',
      title: 'Gorkha Patra Sansthan Building',
      category: 'Commercial',
      clientType: 'government',
      client: 'Federal Project Implementation Unit, Morang',
      description:
        '3.5 Storey RCC frame structure Office Building, 2.5 Storey RCC Quarter Building, Canteen House, Guard House, Printing Plant & Godown. Area 1150.38 sqm, Total Floor Area 1521.60 sqm.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2019',
      highlights: [
        '3.5-storey office building',
        '2.5-storey quarter building',
        'Printing plant & godown',
        '1,521 sqm total floor area',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-16/p-16-small.jpg',
        featured: '/images/project-galleries/project-16/p-16-small.jpg',
        gallery: [
          '/images/project-galleries/project-16/p-16-small.jpg',
        ],
      },
      seo: {
        title: 'Gorkhapatra Sansthan Building | KNSEWA Projects',
        description: 'Gorkhapatra Sansthan office and residential complex in Biratnagar.',
      },
    },
    {
      id: 'project-17',
      slug: 'aarohan-gurukul-theater',
      title: 'Theater Complex cum Residential School for Aarohan Gurukul',
      category: 'Commercial',
      clientType: 'government',
      client: 'Biratnagar Metropolitan City',
      description:
        'RCC Frame Structure Building, Total Floor Area 772.13 sqm. Includes Sanitary, Electrical, HVAC, Furniture Supply, Wooden Parketing and Audio Visual Installation. Theater Hall capacity 400 persons.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2021',
      highlights: [
        '400-seat theater hall',
        'Audio visual installation',
        'Wooden parketing',
        'Residential school facility',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-17/p-17-small.jpg',
        featured: '/images/project-galleries/project-17/3.jpg',
        gallery: [
          '/images/project-galleries/project-17/3.jpg',
          '/images/project-galleries/project-17/p-17-small.jpg',
        ],
      },
      seo: {
        title: 'Aarohan Gurukul Theater | KNSEWA Projects',
        description: 'Theater and residential school complex in Biratnagar.',
      },
    },
    {
      id: 'project-19',
      slug: 'civil-engineering-building-manmohan',
      title: 'Department of Civil Engineering Building',
      category: 'Educational',
      clientType: 'institutional',
      client: 'Manmohan Memorial Polytechnic, Morang',
      description: '2 Storey RCC Frame Structure Building for the Department of Civil Engineering.',
      location: 'Hattimuda-7, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2017',
      highlights: ['2-storey RCC structure', 'Educational facility'],
      images: {
        thumbnail: '/images/project-galleries/project-19/p-19-small.jpg',
        featured: '/images/project-galleries/project-19/1.jpg',
        gallery: [
          '/images/project-galleries/project-19/1.jpg',
          '/images/project-galleries/project-19/2.jpg',
        ],
      },
      seo: {
        title: 'Civil Engineering Building | KNSEWA Projects',
        description: 'Civil engineering department building at Manmohan Memorial Polytechnic.',
      },
    },
    {
      id: 'project-20',
      slug: 'paramedical-building-manmohan',
      title: 'Paramedical Building, Budhiganga-4',
      category: 'Educational',
      clientType: 'institutional',
      client: 'Manmohan Technical University, Morang',
      description:
        'Two and half storey RCC frame structure building with mat foundation (610mm thickness), 1687.36 sqm area. Plinth Area: 1544.70 sqm, Total Floor Area: 3034.76 sqm.',
      location: 'Budhiganga-4, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2022',
      highlights: [
        '2.5-storey RCC building',
        '3,034 sqm total floor area',
        'Mat foundation (610mm)',
        'Full MEP systems',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-20/p-20-small.jpg',
        featured: '/images/project-galleries/project-20/1.jpg',
        gallery: [
          '/images/project-galleries/project-20/1.jpg',
          '/images/project-galleries/project-20/2.jpg',
          '/images/project-galleries/project-20/3.jpg',
        ],
      },
      seo: {
        title: 'Paramedical Building | KNSEWA Projects',
        description: 'Paramedical building at Manmohan Technical University, Morang.',
      },
    },
    {
      id: 'project-21',
      slug: 'district-treasury-office-biratnagar',
      title: 'District Treasury Controller Office Building',
      category: 'Government',
      clientType: 'government',
      client: 'District Treasury Controller Office, Morang',
      description: '2 Storey RCC Frame Structure Building for the District Treasury Controller Office.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2011',
      highlights: ['2-storey government office', 'RCC frame structure'],
      images: {
        thumbnail: '/images/project-galleries/project-21/p-21-small.jpg',
        featured: '/images/project-galleries/project-21/1.jpg',
        gallery: [
          '/images/project-galleries/project-21/1.jpg',
          '/images/project-galleries/project-21/2.jpg',
        ],
      },
      seo: {
        title: 'Treasury Office Building | KNSEWA Projects',
        description: 'District Treasury Controller Office in Biratnagar, Morang.',
      },
    },
    {
      id: 'project-22',
      slug: 'karmachari-sanchaya-kosh-office',
      title: 'Office Building of Karmachari Sanchaya Kosh',
      category: 'Government',
      clientType: 'government',
      client: 'Employees Provident Fund (Karmachari Sanchaya Kosh), Morang',
      description:
        '2 Storey RCC Frame Structure Building, Total Floor Area 7603.74 sq.ft.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2018',
      highlights: ['2-storey office building', '7,603 sq.ft floor area'],
      images: {
        thumbnail: '/images/project-galleries/project-22/p-22-small.jpg',
        featured: '/images/project-galleries/project-22/1.jpg',
        gallery: [
          '/images/project-galleries/project-22/1.jpg',
          '/images/project-galleries/project-22/2.jpg',
        ],
      },
      seo: {
        title: 'Karmachari Sanchaya Kosh Office | KNSEWA Projects',
        description: 'Employees Provident Fund office building in Biratnagar.',
      },
    },
    {
      id: 'project-23',
      slug: 'district-admin-office-biratnagar',
      title: 'District Administration Office, Biratnagar',
      category: 'Government',
      clientType: 'government',
      client: 'District Administration Office, Biratnagar',
      description:
        '3 Storey RCC Frame Structure Building, Plinth Area 5304.68 sq.ft, Total Floor Area 13453.55 sq.ft.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2014',
      highlights: ['3-storey government building', '13,453 sq.ft floor area'],
      images: {
        thumbnail: '/images/project-galleries/project-23/p-7-2.jpg',
        featured: '/images/project-galleries/project-23/1.jpg',
        gallery: [
          '/images/project-galleries/project-23/1.jpg',
          '/images/project-galleries/project-23/2.jpg',
        ],
      },
      seo: {
        title: 'District Admin Office | KNSEWA Projects',
        description: 'District Administration Office building in Biratnagar, Morang.',
      },
    },
    {
      id: 'project-25',
      slug: 'urban-development-office-biratnagar',
      title: 'Office Building of Urban Development & Building Construction',
      category: 'Government',
      clientType: 'government',
      client: 'Dept. of Urban Development & Building Construction, Biratnagar',
      description: '3 Storey RCC Frame Structure Building, Total Floor Area 6000 sq.ft.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2012',
      highlights: ['3-storey office building', '6,000 sq.ft floor area'],
      images: {
        thumbnail: '/images/project-galleries/project-25/p-25-small.jpg',
        featured: '/images/project-galleries/project-25/p-25-small.jpg',
        gallery: [
          '/images/project-galleries/project-25/p-25-small.jpg',
        ],
      },
      seo: {
        title: 'Urban Development Office | KNSEWA Projects',
        description: 'Urban Development & Building Construction office in Biratnagar.',
      },
    },
    {
      id: 'project-26',
      slug: 'jamc-academic-block',
      title: 'Academic Block of Janta Aadarsha Multiple Campus (JAMC)',
      category: 'Educational',
      clientType: 'institutional',
      client: 'Purbanchal University, Biratnagar',
      description: '3 Storey RCC Frame Structure Building for Purbanchal University affiliated campus.',
      location: 'Biratnagar, Morang',
      scope: 'New Construction',
      status: 'completed',
      year: '2022',
      highlights: ['3-storey academic block', 'University campus facility'],
      images: {
        thumbnail: '/images/project-galleries/project-26/p-26-small.jpg',
        featured: '/images/project-galleries/project-26/1.jpg',
        gallery: [
          '/images/project-galleries/project-26/1.jpg',
        ],
      },
      seo: {
        title: 'JAMC Academic Block | KNSEWA Projects',
        description: 'Academic block at Janta Aadarsha Multiple Campus, Biratnagar.',
      },
    },
    {
      id: 'project-27',
      slug: 'inaruwa-substation-staff-quarter',
      title: 'Staff Quarter at Inaruwa Substation',
      category: 'Government',
      clientType: 'government',
      client: 'Nepal Electricity Authority (Hetauda-Dhalkebar-Inaruwa 400kV Project)',
      description:
        'Staff Quarter, Store House & Guard House at Inaruwa Substation. RCC frame building including sanitary and electrical work. Total floor area 549.78 sqm.',
      location: 'Inaruwa, Sunsari',
      scope: 'New Construction',
      status: 'completed',
      year: '2022',
      highlights: [
        'NEA 400kV substation project',
        'Staff quarters & guard house',
        '549 sqm floor area',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-27/p-27-small.jpg',
        featured: '/images/project-galleries/project-27/1.jpg',
        gallery: [
          '/images/project-galleries/project-27/1.jpg',
          '/images/project-galleries/project-27/2.jpg',
          '/images/project-galleries/project-27/3.jpg',
          '/images/project-galleries/project-27/4.jpg',
        ],
      },
      seo: {
        title: 'Inaruwa Substation Staff Quarter | KNSEWA Projects',
        description: 'Staff quarters at NEA Inaruwa 400kV substation, Sunsari.',
      },
    },
    {
      id: 'project-31',
      slug: 'rcc-overhead-tank-biratnagar',
      title: '450 Cum Capacity RCC Overhead Tank',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Federal Water Supply & Sewerage Management Project, Biratnagar',
      description:
        '450 Cum Capacity RCC Overhead Tank, Pipe line installation & fitting Works, Installation of Submersible Pump, Leak Proof Test, Supply & Installation of Electrical Works.',
      location: 'Pichra, Biratnagar, Morang',
      scope: 'Water Supply',
      status: 'completed',
      year: '2014',
      highlights: [
        '450 cum capacity',
        'Submersible pump installation',
        'Complete electrical works',
      ],
      images: {
        thumbnail: '/images/project-galleries/project-31/p-31-small.jpg',
        featured: '/images/project-galleries/project-31/p-31-small.jpg',
        gallery: [
          '/images/project-galleries/project-31/p-31-small.jpg',
        ],
      },
      seo: {
        title: 'RCC Overhead Tank | KNSEWA Projects',
        description: '450 cum RCC overhead tank at Pichra, Biratnagar.',
      },
    },

    // ── New projects from General Construction Experience PDF ──

    {
      id: 'project-34',
      slug: 'rcc-bridge-simariya-road',
      title: 'RCC Bridge Construction, Simariya Road',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Sunsari-Morang Bridge Construction Project, Sunsari',
      description: 'RCC bridge construction on Simariya Road, Morang. Part of the Sunsari-Morang Bridge Construction Project.',
      location: 'Simariya Road, Morang',
      scope: 'Bridge Construction',
      status: 'completed',
      year: '2009',
      highlights: ['RCC Bridge', 'Simariya Road', 'Sunsari-Morang Bridge Project'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'RCC Bridge Simariya Road | KNSEWA Projects',
        description: 'RCC bridge construction on Simariya Road, Morang.',
      },
    },
    {
      id: 'project-35',
      slug: 'rcc-overhead-tank-mangsuwa',
      title: '450m³ RCC Overhead Water Tank, Mangsuwa',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Water Supply & Sanitation Division Office, Morang',
      description: '450m³ RCC overhead water tank construction for community water supply in Mangsuwa area.',
      location: 'Mangsuwa, Morang',
      scope: 'Water Infrastructure',
      status: 'completed',
      year: '2009',
      highlights: ['450m³ Capacity', 'RCC Construction', 'Water Supply'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: '450m³ RCC Overhead Tank Mangsuwa | KNSEWA Projects',
        description: '450m³ RCC overhead water tank construction in Mangsuwa, Morang.',
      },
    },
    {
      id: 'project-36',
      slug: 'dormitory-lutheran-world-federation',
      title: '3-Storeys Dormitory Building, Lutheran World Federation',
      category: 'Commercial',
      clientType: 'institutional',
      client: 'Lutheran World Federation, Kathmandu',
      description: '3-storey dormitory building constructed for the Lutheran World Federation in Kathmandu.',
      location: 'Kathmandu',
      scope: 'Dormitory Building',
      status: 'completed',
      year: '2006',
      highlights: ['3-Storey Building', 'Dormitory Facility', 'International Organization'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Dormitory Building Lutheran World Federation | KNSEWA Projects',
        description: '3-storey dormitory building for Lutheran World Federation, Kathmandu.',
      },
    },
    {
      id: 'project-37',
      slug: 'warehouse-district-election-office',
      title: 'Ware House Construction, District Election Office',
      category: 'Government',
      clientType: 'government',
      client: 'District Election Office, Morang',
      description: 'Warehouse construction for the District Election Office in Morang.',
      location: 'Morang',
      scope: 'Warehouse Construction',
      status: 'completed',
      year: '2008',
      highlights: ['Warehouse Facility', 'Government Storage', 'Election Office'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Warehouse District Election Office | KNSEWA Projects',
        description: 'Warehouse construction for District Election Office, Morang.',
      },
    },
    {
      id: 'project-38',
      slug: 'compound-wall-ard-usaid',
      title: 'Compound Wall, Buildings, Slab Culvert & Garage',
      category: 'Government',
      clientType: 'government',
      client: 'ARD/USAID/NGCPP-Nepal',
      description: 'Construction of compound wall, buildings, slab culvert, and garage for the ARD/USAID/NGCPP-Nepal project.',
      location: 'Morang',
      scope: 'Infrastructure & Buildings',
      status: 'completed',
      year: '2010',
      highlights: ['Compound Wall', 'Slab Culvert', 'International Development Project'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'ARD/USAID/NGCPP Infrastructure | KNSEWA Projects',
        description: 'Compound wall, buildings, slab culvert and garage for ARD/USAID/NGCPP-Nepal.',
      },
    },
    {
      id: 'project-39',
      slug: 'warehouse-district-admin-sunsari',
      title: 'Ware House & Infrastructures, District Admin Office, Sunsari',
      category: 'Government',
      clientType: 'government',
      client: 'District Admin. Office, Sunsari',
      description: 'Construction of warehouse and infrastructure including compound wall at the District Administration Office, Sunsari.',
      location: 'Sunsari',
      scope: 'Warehouse & Infrastructure',
      status: 'completed',
      year: '2011',
      highlights: ['Warehouse', 'Compound Wall', 'Government Infrastructure'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Warehouse District Admin Office Sunsari | KNSEWA Projects',
        description: 'Warehouse and infrastructure at District Admin Office, Sunsari.',
      },
    },
    {
      id: 'project-40',
      slug: 'child-correction-home-morang',
      title: 'Child Correction Home',
      category: 'Government',
      clientType: 'government',
      client: 'Mahila Bal-bikas & Samaj Kalyan, Morang',
      description: 'Construction of child correction home for the Department of Women, Children and Social Welfare in Morang.',
      location: 'Morang',
      scope: 'Institutional Building',
      status: 'completed',
      year: '2009',
      highlights: ['Child Welfare Facility', 'Government Institution', 'Social Infrastructure'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Child Correction Home | KNSEWA Projects',
        description: 'Child correction home construction in Morang.',
      },
    },
    {
      id: 'project-41',
      slug: 'pakali-mahendra-nagar-chatra-road',
      title: 'Pakali-Mahendra Nagar-Chatra Road Sub-Project',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'RRRSDP, DPO, Sunsari',
      description: 'Road sub-project under the Rural Reconstruction and Rehabilitation Sector Development Program (RRRSDP) connecting Pakali to Mahendra Nagar via Chatra.',
      location: 'Sunsari',
      scope: 'Road Construction',
      status: 'completed',
      year: '2010',
      highlights: ['Road Sub-Project', 'RRRSDP', 'Rural Road Network'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Pakali-Mahendra Nagar Road | KNSEWA Projects',
        description: 'Pakali-Mahendra Nagar-Chatra road sub-project in Sunsari.',
      },
    },
    {
      id: 'project-42',
      slug: 'office-ministry-agriculture-morang',
      title: 'Office Building, Ministry of Agriculture & Co-operative',
      category: 'Government',
      clientType: 'government',
      client: 'Ministry of Agriculture & Co-operative, Department of Co-operative, Division Co-operative Office (DCO), Morang, Nepal',
      description: 'Office building construction for the Ministry of Agriculture and Co-operative Department in Morang.',
      location: 'Morang',
      scope: 'Government Office',
      status: 'completed',
      year: '2012',
      highlights: ['Ministry Office', 'Co-operative Department', 'Government Building'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Ministry of Agriculture Office | KNSEWA Projects',
        description: 'Office building for Ministry of Agriculture & Co-operative, Morang.',
      },
    },
    {
      id: 'project-43',
      slug: 'innaruwa-duhabi-ithari-dharan-corridor',
      title: 'Infrastructure Development, Innaruwa-Duhabi-Ithari-Dharan Corridor',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Department of Urban Development and Building Construction (DUDBC), Division Office, Morang',
      description: 'SBD infrastructure development work along the Innaruwa-Duhabi-Ithari-Dharan corridor under the DUDBC program.',
      location: 'Morang',
      scope: 'Infrastructure Development',
      status: 'completed',
      year: '2012',
      highlights: ['Urban Corridor', 'DUDBC Project', 'Multi-city Infrastructure'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Innaruwa-Duhabi-Ithari-Dharan Corridor | KNSEWA Projects',
        description: 'Infrastructure development along Innaruwa-Duhabi-Ithari-Dharan corridor.',
      },
    },
    {
      id: 'project-44',
      slug: 'nepal-telecom-exchange-building',
      title: 'Exchange Building, Nepal Telecom, Biratnagar',
      category: 'Commercial',
      clientType: 'government',
      client: 'Nepal Telecom, Eastern Regional Directorate, Biratnagar',
      description: 'Construction of exchange building at Roadsesh, Biratnagar for Nepal Telecom Eastern Regional Directorate.',
      location: 'Roadsesh, Biratnagar, Morang',
      scope: 'Commercial Building',
      status: 'completed',
      year: '2013',
      highlights: ['Telecom Exchange', 'Nepal Telecom', 'Eastern Regional Directorate'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Nepal Telecom Exchange Building | KNSEWA Projects',
        description: 'Exchange building for Nepal Telecom at Roadsesh, Biratnagar.',
      },
    },
    {
      id: 'project-45',
      slug: 'canal-structures-eastern-irrigation',
      title: 'Canal and Structures, Eastern Irrigation Development Division',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Eastern Irrigation Development Division No.-2, Sunsari',
      description: 'Construction of canal and associated structures for the Eastern Irrigation Development Division in Sunsari.',
      location: 'Sunsari',
      scope: 'Irrigation',
      status: 'completed',
      year: '2013',
      highlights: ['Canal Construction', 'Irrigation Structures', 'Eastern Region'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Canal & Structures Eastern Irrigation | KNSEWA Projects',
        description: 'Canal and structures for Eastern Irrigation Development Division, Sunsari.',
      },
    },
    {
      id: 'project-46',
      slug: 'desilting-cmc-chatra-main-canal',
      title: 'Desilting Works of CMC, Chatra Main Canal',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Sunsari-Morang Irrigation Project, Biratnagar',
      description: 'Desilting works of CMC on Chatra Main Canal (ch 36+200 to 39+200 km) for the Sunsari-Morang Irrigation Project.',
      location: 'Biratnagar',
      scope: 'Canal Maintenance',
      status: 'completed',
      year: '2014',
      highlights: ['Desilting Works', 'Chatra Main Canal', 'Sunsari-Morang Irrigation'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Desilting Chatra Main Canal | KNSEWA Projects',
        description: 'Desilting works of CMC, Chatra Main Canal, Biratnagar.',
      },
    },
    {
      id: 'project-47',
      slug: 'cottage-small-industry-office',
      title: 'Cottage & Small Industry Office Building',
      category: 'Government',
      clientType: 'government',
      client: 'Cottage & Small Industry Office, Biratnagar, Morang',
      description: 'Construction of office building for the Cottage and Small Industry Office in Biratnagar.',
      location: 'Biratnagar, Morang',
      scope: 'Government Office',
      status: 'completed',
      year: '2014',
      highlights: ['Industry Office', 'Government Building', 'Biratnagar'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Cottage & Small Industry Office | KNSEWA Projects',
        description: 'Cottage & Small Industry Office building construction, Biratnagar.',
      },
    },
    {
      id: 'project-48',
      slug: 'kocheni-khola-rcc-bridge',
      title: 'Kocheni Khola RCC Girder Bridge',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'District Development Committee, Biratnagar, Morang',
      description: 'Construction of Kocheni Khola RCC girder bridge in Biratnagar under the District Development Committee.',
      location: 'Biratnagar, Morang',
      scope: 'Bridge Construction',
      status: 'completed',
      year: '2014',
      highlights: ['RCC Girder Bridge', 'Kocheni Khola', 'District Development'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Kocheni Khola RCC Bridge | KNSEWA Projects',
        description: 'Kocheni Khola RCC girder bridge construction in Biratnagar.',
      },
    },
    {
      id: 'project-49',
      slug: 'rcc-overhead-tank-225cum',
      title: 'RCC Overhead Water Storage Tank (225 CUm)',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Water Supply & Sanitation Division Office, Morang',
      description: 'Construction of 225 CUm capacity RCC overhead water storage tank for the Water Supply and Sanitation Division.',
      location: 'Morang',
      scope: 'Water Infrastructure',
      status: 'completed',
      year: '2015',
      highlights: ['225 CUm Capacity', 'Overhead Tank', 'Water Storage'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'RCC Overhead Tank 225 CUm | KNSEWA Projects',
        description: 'RCC overhead water storage tank (225 CUm) construction in Morang.',
      },
    },
    {
      id: 'project-50',
      slug: 'helipad-biratnagar-airport',
      title: 'Helipad at Biratnagar Airport',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Civil Aviation Authority of Nepal, Babarmahal, Kathmandu',
      description: 'Construction of helipad at Biratnagar Airport for the Civil Aviation Authority of Nepal.',
      location: 'Biratnagar',
      scope: 'Aviation Infrastructure',
      status: 'completed',
      year: '2015',
      highlights: ['Helipad Construction', 'Biratnagar Airport', 'Civil Aviation'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Helipad Biratnagar Airport | KNSEWA Projects',
        description: 'Helipad construction at Biratnagar Airport.',
      },
    },
    {
      id: 'project-51',
      slug: 'blacktopped-road-jhapa-morang',
      title: 'Blacktopped Road Construction Works, Jhapa-Morang',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Division Road Office, Morang',
      description: 'Blacktopped road construction works including drainage structures on Jhapa Baijanathpur Milanchowk 7,8,9 Katahari 2,3 Adarshanagar-Bhatigunj Road, Morang.',
      location: 'Morang',
      scope: 'Road Construction',
      status: 'completed',
      year: '2015',
      highlights: ['Blacktopped Road', 'Drainage Structures', 'Multi-location'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Blacktopped Road Jhapa-Morang | KNSEWA Projects',
        description: 'Blacktopped road construction works including drainage structures in Jhapa-Morang.',
      },
    },
    {
      id: 'project-52',
      slug: 'water-tank-simara-sez',
      title: 'Overhead Water Tank and Deep Tube Well, Simara SEZ',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Special Economic Zone Development Committee, Babarmahal, Kathmandu, Nepal',
      description: 'Construction of overhead water tank and deep tube well in GPZ of Block A, Simara SEZ, District Bara for the Special Economic Zone Development Committee.',
      location: 'Simara SEZ, Bara',
      scope: 'Water Infrastructure',
      status: 'completed',
      year: '2018',
      highlights: ['Overhead Water Tank', 'Deep Tube Well', 'Special Economic Zone'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Water Tank Simara SEZ | KNSEWA Projects',
        description: 'Overhead water tank and deep tube well at Simara Special Economic Zone.',
      },
    },
    {
      id: 'project-53',
      slug: 'warehouse-nepal-red-cross-itahari',
      title: 'Warehouse & Boundary Wall, Nepal Red Cross Society',
      category: 'Commercial',
      clientType: 'institutional',
      client: 'Nepal Red Cross Society, Kalimati, Kathmandu',
      description: 'Construction of warehouse and boundary wall at Itahari, Sunsari for Nepal Red Cross Society.',
      location: 'Itahari, Sunsari',
      scope: 'Warehouse & Infrastructure',
      status: 'completed',
      year: '2019',
      highlights: ['Warehouse', 'Boundary Wall', 'Nepal Red Cross Society'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Nepal Red Cross Warehouse Itahari | KNSEWA Projects',
        description: 'Warehouse and boundary wall for Nepal Red Cross Society at Itahari, Sunsari.',
      },
    },
    {
      id: 'project-54',
      slug: 'staff-quarter-nea-india-transmission',
      title: 'Staff Quarter, Store & Guard House, NEA Nepal-India Electricity',
      category: 'Government',
      clientType: 'government',
      client: 'NEA, Transmission Directorate, Nepal-India Electricity Transmission & Trade Project',
      description: 'Construction of staff quarter, store and guard house at Inaruwa, Sunsari for the Nepal-India Electricity Transmission and Trade Project under NEA Transmission Directorate.',
      location: 'Inaruwa, Sunsari',
      scope: 'Staff Quarters',
      status: 'completed',
      year: '2019',
      highlights: ['NEA Transmission Project', 'Nepal-India Electricity', 'Staff Quarter & Store'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'NEA Nepal-India Transmission Staff Quarter | KNSEWA Projects',
        description: 'Staff quarter, store and guard house for NEA Nepal-India Electricity Transmission project.',
      },
    },
    {
      id: 'project-55',
      slug: 'office-infrastructures-district-admin-morang',
      title: 'Office Building & Infrastructures, District Admin Office, Morang',
      category: 'Government',
      clientType: 'government',
      client: 'District Admin. Office, Morang',
      description: 'Construction of office building and infrastructures at the District Administration Office, Morang.',
      location: 'Morang',
      scope: 'Government Office',
      status: 'completed',
      year: '2011',
      highlights: ['Office Building', 'Government Infrastructure', 'District Administration'],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'District Admin Office Morang | KNSEWA Projects',
        description: 'Office building and infrastructures at District Admin Office, Morang.',
      },
    },
    {
      id: 'project-56',
      slug: 'timai-shantinagar-water-supply-jhapa',
      title: 'Timai Shantinagar Integrated Water Supply Project',
      category: 'Infrastructure',
      clientType: 'government',
      client: 'Federal Water Supply & Sewerage Management Project, Biratnagar',
      description: 'Entire construction work of Timai Shantinagar integrated water supply project covering Buddhashanti Rural Municipality wards 4, 5, 6 & 7 in Jhapa district.',
      location: 'Buddhashanti Municipality, Jhapa',
      scope: 'Water Supply',
      status: 'running',
      completionPercentage: 90,
      contractValue: 'NPR 114.9M',
      year: '2024',
      highlights: [
        'Integrated water supply',
        'Multi-ward coverage (4,5,6,7)',
        'Federal project',
        'Buddhashanti Municipality',
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'Timai Shantinagar Water Supply | KNSEWA Projects',
        description: 'Integrated water supply project at Buddhashanti Municipality, Jhapa.',
      },
    },
    {
      id: 'project-57',
      slug: 'mch-block-purbanchal-university-morang',
      title: 'Ground Floor of MCH Block at Purbanchal University',
      category: 'Healthcare',
      clientType: 'institutional',
      client: 'Purbanchal University, Central Office (PU)',
      description: 'Construction of ground floor of MCH (Maternal and Child Health) block at Purbanchal University, Sundarharaincha, Gothgaun, Morang.',
      location: 'Sundarharaincha, Gothgaun, Morang',
      scope: 'Healthcare Facility',
      status: 'running',
      completionPercentage: 20,
      contractValue: 'NPR 120.5M',
      year: '2025',
      highlights: [
        'MCH Block',
        'Purbanchal University campus',
        'Healthcare infrastructure',
        'Ground floor construction',
      ],
      images: {
        thumbnail: '/images/projects/placeholder.jpg',
        featured: '/images/projects/placeholder.jpg',
        gallery: [],
      },
      seo: {
        title: 'MCH Block Purbanchal University | KNSEWA Projects',
        description: 'Ground floor MCH block at Purbanchal University, Gothgaun, Morang.',
      },
    },
  ],

  cta: {
    label: 'Start Your Project',
    headline: 'Have a Project in Mind?',
    description:
      'From concept to completion, our experienced team delivers results. Let\'s discuss how we can bring your construction vision to life.',
    primaryCTA: {
      text: 'Contact Us',
      href: '/contact',
    },
    secondaryCTA: {
      text: 'Our Services',
      href: '/services',
    },
  },
};
