import type { Project } from '@/types/content';

/**
 * All KNSEWA projects — single source of truth.
 * Used by homepage (featured), /projects page, etc.
 */
export const allProjects: Project[] = [
  {
    id: 'project-1',
    slug: 'deerwalk-complex-kathmandu',
    title: 'Basement + G + 4 Building at Deerwalk Complex, Sifal, Kathmandu',
    category: 'Educational',
    clientType: 'institutional',
    location: 'Kathmandu',
    scope: 'Educational Complex',
    highlights: ['Basement + G + 4 Floors', 'IT Campus', 'Modern Design'],
    images: {
      thumbnail: '/images/projects/legacy/project-1.jpg',
      featured: '/images/projects/legacy/project-1.jpg',
      gallery: [],
    },
    seo: {
      title: 'Deerwalk Complex Building | KNS Projects',
      description: 'Basement + G + 4 building at Deerwalk Complex in Sifal, Kathmandu.',
    },
  },
  {
    id: 'project-2',
    slug: 'baikunthe-drinking-water-chitwan',
    title: 'Baikunthe Underground Drinking Water Project, Madi, Chitwan',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Chitwan',
    scope: 'Water Supply',
    highlights: ['Underground System', 'Community Water Supply', 'Rural Development'],
    images: {
      thumbnail: '/images/projects/legacy/project-2.jpg',
      featured: '/images/projects/legacy/project-2.jpg',
      gallery: [],
    },
    seo: {
      title: 'Baikunthe Drinking Water Project | KNS Projects',
      description: 'Underground drinking water project in Madi, Chitwan, Nepal.',
    },
  },
  {
    id: 'project-3',
    slug: 'sewerage-treatment-letang',
    title: 'Sewerage and Treatment Plant in Letang, Morang',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Water Treatment & Sanitation',
    highlights: ['Sewerage System', 'Treatment Plant', 'Environmental'],
    images: {
      thumbnail: '/images/projects/legacy/project-3.jpg',
      featured: '/images/projects/legacy/project-3.jpg',
      gallery: [],
    },
    seo: {
      title: 'Sewerage and Treatment Plant | KNS Projects',
      description: 'Sewerage and treatment plant construction in Letang, Morang.',
    },
  },
  {
    id: 'project-4',
    slug: 'pathari-sanischare-hospital',
    title: '15 Bedded Pathari Sanischare Municipal Hospital',
    category: 'Healthcare',
    clientType: 'government',
    location: 'Morang',
    scope: 'Healthcare Facility',
    highlights: ['15 Beds', 'Municipal Hospital', 'Public Healthcare'],
    images: {
      thumbnail: '/images/projects/legacy/project-4.jpg',
      featured: '/images/projects/legacy/project-4.jpg',
      gallery: [],
    },
    seo: {
      title: 'Pathari Sanischare Municipal Hospital | KNS Projects',
      description: '15 bedded municipal hospital at Pathari Sanischare, Morang.',
    },
  },
  {
    id: 'project-5',
    slug: 'pathari-khola-bridge',
    title: 'Buddha Marga ko Pathari Khola ma Pul Nirman, Pathari, Morang',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Bridge Construction',
    highlights: ['Bridge Construction', 'Buddha Marga', 'Connectivity'],
    images: {
      thumbnail: '/images/projects/legacy/project-5.jpg',
      featured: '/images/projects/legacy/project-5.jpg',
      gallery: [],
    },
    seo: {
      title: 'Pathari Khola Bridge | KNS Projects',
      description: 'Bridge construction over Pathari Khola on Buddha Marga, Morang.',
    },
  },
  {
    id: 'project-6',
    slug: 'jahada-municipal-hospital',
    title: '15 Bedded Municipal Hospital at Jahada, Morang',
    category: 'Healthcare',
    clientType: 'government',
    location: 'Morang',
    scope: 'Healthcare Facility',
    highlights: ['15 Beds', 'Municipal Hospital', 'Rural Healthcare'],
    images: {
      thumbnail: '/images/projects/legacy/project-6.jpg',
      featured: '/images/projects/legacy/project-6.jpg',
      gallery: [],
    },
    seo: {
      title: 'Jahada Municipal Hospital | KNS Projects',
      description: '15 bedded municipal hospital at Jahada, Morang.',
    },
  },
  {
    id: 'project-7',
    slug: 'jahada-administration-building',
    title: 'Administration Building at Jahada-5, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Morang',
    scope: 'Administrative Building',
    highlights: ['Government Office', 'Administrative Hub', 'Public Service'],
    images: {
      thumbnail: '/images/projects/legacy/project-7.jpg',
      featured: '/images/projects/legacy/project-7.jpg',
      gallery: [],
    },
    seo: {
      title: 'Jahada Administration Building | KNS Projects',
      description: 'Administration building at Jahada-5, Morang.',
    },
  },
  {
    id: 'project-8',
    slug: 'prime-minister-park-biratnagar',
    title: 'Prime Minister Park at Biratnagar, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Public Park',
    highlights: ['Public Park', 'Urban Development', 'Landmark Project'],
    images: {
      thumbnail: '/images/projects/legacy/project-8.jpg',
      featured: '/images/projects/legacy/project-8.jpg',
      gallery: [],
    },
    seo: {
      title: 'Prime Minister Park | KNS Projects',
      description: 'Prime Minister Park at Biratnagar, Morang.',
    },
  },
  {
    id: 'project-9',
    slug: 'patan-secondary-school',
    title: 'Patan Secondary School at Patandhoka in Lalitpur District',
    category: 'Educational',
    clientType: 'institutional',
    location: 'Lalitpur',
    scope: 'School Building',
    highlights: ['Secondary School', 'Educational Infrastructure', 'Lalitpur'],
    images: {
      thumbnail: '/images/projects/legacy/project-9.jpg',
      featured: '/images/projects/legacy/project-9.jpg',
      gallery: [],
    },
    seo: {
      title: 'Patan Secondary School | KNS Projects',
      description: 'Patan Secondary School at Patandhoka, Lalitpur District.',
    },
  },
  {
    id: 'project-10',
    slug: 'admin-building-kavrepalanchowk',
    title: 'Administrative Building and Land Development, Kavrepalanchowk',
    category: 'Government',
    clientType: 'government',
    location: 'Kavrepalanchowk',
    scope: 'Administrative Building',
    highlights: ['Admin Building', 'Land Development', 'Government'],
    images: {
      thumbnail: '/images/projects/legacy/project-10.jpg',
      featured: '/images/projects/legacy/project-10.jpg',
      gallery: [],
    },
    seo: {
      title: 'Administrative Building Kavrepalanchowk | KNS Projects',
      description: 'Administrative building and land development in Kavrepalanchowk.',
    },
  },
  {
    id: 'project-12',
    slug: 'mangadh-water-supply-biratnagar',
    title: 'Mangadh Sahalagani Water Supply and Sanitation Project, Biratnagar, Morang',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Water Supply & Sanitation',
    highlights: ['Water Supply', 'Sanitation', 'Community Project'],
    images: {
      thumbnail: '/images/projects/legacy/project-12.jpg',
      featured: '/images/projects/legacy/project-12.jpg',
      gallery: [],
    },
    seo: {
      title: 'Mangadh Water Supply Project | KNS Projects',
      description: 'Water supply and sanitation project in Biratnagar, Morang.',
    },
  },
  {
    id: 'project-13',
    slug: 'kiratichowk-birendranagar-road',
    title: 'Kiratichowk Birendranagar Road, Pathari Sanischare Municipality',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Road Construction',
    highlights: ['Road Construction', 'Municipal Road', 'Connectivity'],
    images: {
      thumbnail: '/images/projects/legacy/project-13.jpg',
      featured: '/images/projects/legacy/project-13.jpg',
      gallery: [],
    },
    seo: {
      title: 'Kiratichowk Birendranagar Road | KNS Projects',
      description: 'Road construction at Pathari Sanischare Municipality, Morang.',
    },
  },
  {
    id: 'project-14',
    slug: 'stormwater-concrete-drain',
    title: 'Stormwater Concrete Drain',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Drainage System',
    highlights: ['Stormwater Drain', 'Concrete Construction', 'Urban Infrastructure'],
    images: {
      thumbnail: '/images/projects/legacy/project-14.jpg',
      featured: '/images/projects/legacy/project-14.jpg',
      gallery: [],
    },
    seo: {
      title: 'Stormwater Concrete Drain | KNS Projects',
      description: 'Stormwater concrete drain construction project.',
    },
  },
  {
    id: 'project-16',
    slug: 'gorkha-patra-sansthan-building',
    title: 'Gorkha Patra Sansthan Building',
    category: 'Commercial',
    clientType: 'commercial',
    location: 'Biratnagar',
    scope: 'Commercial Building',
    highlights: ['Media House', 'Commercial Building', 'Institutional'],
    images: {
      thumbnail: '/images/projects/legacy/project-16.jpg',
      featured: '/images/projects/legacy/project-16.jpg',
      gallery: [],
    },
    seo: {
      title: 'Gorkha Patra Sansthan Building | KNS Projects',
      description: 'Gorkha Patra Sansthan commercial building construction.',
    },
  },
  {
    id: 'project-17',
    slug: 'aarohan-gurukul-biratnagar',
    title: 'Theater Complex cum Residential School for Aarohan Gurukul, Biratnagar, Morang',
    category: 'Commercial',
    clientType: 'commercial',
    location: 'Biratnagar',
    scope: 'Theater & School Complex',
    highlights: ['Theater Complex', 'Residential School', 'Cultural Hub'],
    images: {
      thumbnail: '/images/projects/legacy/project-17.jpg',
      featured: '/images/projects/legacy/project-17.jpg',
      gallery: [],
    },
    seo: {
      title: 'Aarohan Gurukul Complex | KNS Projects',
      description: 'Theater complex and residential school for Aarohan Gurukul in Biratnagar.',
    },
  },
  {
    id: 'project-19',
    slug: 'civil-engineering-department-building',
    title: 'Department of Civil Engineering Building',
    category: 'Government',
    clientType: 'government',
    location: 'Morang',
    scope: 'Government Building',
    highlights: ['Engineering Department', 'Government Office', 'Institutional'],
    images: {
      thumbnail: '/images/projects/legacy/project-19.jpg',
      featured: '/images/projects/legacy/project-19.jpg',
      gallery: [],
    },
    seo: {
      title: 'Civil Engineering Department Building | KNS Projects',
      description: 'Department of Civil Engineering building construction.',
    },
  },
  {
    id: 'project-20',
    slug: 'paramedical-building-budhiganga',
    title: 'Paramedical Building, Budhiganga-4, Morang',
    category: 'Commercial',
    clientType: 'commercial',
    location: 'Morang',
    scope: 'Medical Building',
    highlights: ['Paramedical Facility', 'Healthcare Infrastructure', 'Commercial'],
    images: {
      thumbnail: '/images/projects/legacy/project-20.jpg',
      featured: '/images/projects/legacy/project-20.jpg',
      gallery: [],
    },
    seo: {
      title: 'Paramedical Building | KNS Projects',
      description: 'Paramedical building at Budhiganga-4, Morang.',
    },
  },
  {
    id: 'project-21',
    slug: 'district-treasury-office-biratnagar',
    title: 'District Treasury Controller (Ko. Le. Ni. Ka.) Office Building, Biratnagar, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Government Office',
    highlights: ['Treasury Office', 'Government Building', 'Administrative'],
    images: {
      thumbnail: '/images/projects/legacy/project-21.jpg',
      featured: '/images/projects/legacy/project-21.jpg',
      gallery: [],
    },
    seo: {
      title: 'District Treasury Controller Office | KNS Projects',
      description: 'District Treasury Controller office building in Biratnagar, Morang.',
    },
  },
  {
    id: 'project-22',
    slug: 'karmachari-sanchaya-kosh-office',
    title: 'Office Building of Karmachari Sanchaya Kosh',
    category: 'Government',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Government Office',
    highlights: ['Provident Fund Office', 'Government Building', 'Financial Institution'],
    images: {
      thumbnail: '/images/projects/legacy/project-22.jpg',
      featured: '/images/projects/legacy/project-22.jpg',
      gallery: [],
    },
    seo: {
      title: 'Karmachari Sanchaya Kosh Office | KNS Projects',
      description: 'Office building of Karmachari Sanchaya Kosh.',
    },
  },
  {
    id: 'project-23',
    slug: 'district-administration-office-biratnagar',
    title: 'District Administration Office, Biratnagar, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Government Office',
    highlights: ['District Admin Office', 'Government Hub', 'Public Service'],
    images: {
      thumbnail: '/images/projects/legacy/project-23.jpg',
      featured: '/images/projects/legacy/project-23.jpg',
      gallery: [],
    },
    seo: {
      title: 'District Administration Office | KNS Projects',
      description: 'District Administration Office in Biratnagar, Morang.',
    },
  },
  {
    id: 'project-25',
    slug: 'urban-development-office-biratnagar',
    title: 'Office Building of Urban Development & Building Construction, Biratnagar, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Government Office',
    highlights: ['Urban Development', 'Building Construction Dept', 'Government'],
    images: {
      thumbnail: '/images/projects/legacy/project-25.jpg',
      featured: '/images/projects/legacy/project-25.jpg',
      gallery: [],
    },
    seo: {
      title: 'Urban Development Office | KNS Projects',
      description: 'Office of Urban Development & Building Construction in Biratnagar.',
    },
  },
  {
    id: 'project-26',
    slug: 'jamc-academic-block-biratnagar',
    title: 'Academic Block of Janta Aadarsha Multiple Campus (JAMC), PU, Biratnagar, Morang',
    category: 'Educational',
    clientType: 'institutional',
    location: 'Biratnagar',
    scope: 'Academic Building',
    highlights: ['Academic Block', 'University Campus', 'Educational'],
    images: {
      thumbnail: '/images/projects/legacy/project-26.jpg',
      featured: '/images/projects/legacy/project-26.jpg',
      gallery: [],
    },
    seo: {
      title: 'JAMC Academic Block | KNS Projects',
      description: 'Academic block of Janta Aadarsha Multiple Campus in Biratnagar.',
    },
  },
  {
    id: 'project-27',
    slug: 'staff-quarter-inaruwa-substation',
    title: 'Staff Quarter at Inaruwa Substation, Inaruwa, Sunsari',
    category: 'Government',
    clientType: 'government',
    location: 'Sunsari',
    scope: 'Staff Quarters',
    highlights: ['Staff Quarter', 'Power Substation', 'Government Housing'],
    images: {
      thumbnail: '/images/projects/legacy/project-27.jpg',
      featured: '/images/projects/legacy/project-27.jpg',
      gallery: [],
    },
    seo: {
      title: 'Inaruwa Substation Staff Quarter | KNS Projects',
      description: 'Staff quarter at Inaruwa substation in Sunsari.',
    },
  },
  {
    id: 'project-31',
    slug: 'rcc-overhead-tank',
    title: '450 Cum Capacity RCC Overhead Tank',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Water Infrastructure',
    highlights: ['450 Cum Capacity', 'RCC Construction', 'Water Storage'],
    images: {
      thumbnail: '/images/projects/legacy/project-31.jpg',
      featured: '/images/projects/legacy/project-31.jpg',
      gallery: [],
    },
    seo: {
      title: '450 Cum RCC Overhead Tank | KNS Projects',
      description: '450 cum capacity RCC overhead tank construction.',
    },
  },
];

/** All unique project categories */
export const projectCategories = [
  'Commercial',
  'Educational',
  'Government',
  'Healthcare',
  'Infrastructure',
];
