import type { Project } from '@/types/content';

/**
 * All KNSEWA projects — single source of truth.
 * Used by homepage (featured), /projects page, etc.
 */
export const allProjects: Project[] = [
  {
    id: 'project-1',
    slug: 'deerwalk-complex-kathmandu',
    title: 'Basement + G + 4 Building at Deerwalk Complex, Sifal, Kathmandu',
    category: 'Educational',
    clientType: 'institutional',
    location: 'Kathmandu',
    scope: 'Educational Complex',
    highlights: ['Basement + G + 4 Floors', 'IT Campus', 'Modern Design'],
    images: {
      thumbnail: '/images/projects/legacy/project-1.jpg',
      featured: '/images/projects/legacy/project-1.jpg',
      gallery: [],
    },
    seo: {
      title: 'Deerwalk Complex Building | KNS Projects',
      description: 'Basement + G + 4 building at Deerwalk Complex in Sifal, Kathmandu.',
    },
  },
  {
    id: 'project-2',
    slug: 'baikunthe-drinking-water-chitwan',
    title: 'Baikunthe Underground Drinking Water Project, Madi, Chitwan',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Chitwan',
    scope: 'Water Supply',
    highlights: ['Underground System', 'Community Water Supply', 'Rural Development'],
    images: {
      thumbnail: '/images/projects/legacy/project-2.jpg',
      featured: '/images/projects/legacy/project-2.jpg',
      gallery: [],
    },
    seo: {
      title: 'Baikunthe Drinking Water Project | KNS Projects',
      description: 'Underground drinking water project in Madi, Chitwan, Nepal.',
    },
  },
  {
    id: 'project-3',
    slug: 'sewerage-treatment-letang',
    title: 'Sewerage and Treatment Plant in Letang, Morang',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Water Treatment & Sanitation',
    highlights: ['Sewerage System', 'Treatment Plant', 'Environmental'],
    images: {
      thumbnail: '/images/projects/legacy/project-3.jpg',
      featured: '/images/projects/legacy/project-3.jpg',
      gallery: [],
    },
    seo: {
      title: 'Sewerage and Treatment Plant | KNS Projects',
      description: 'Sewerage and treatment plant construction in Letang, Morang.',
    },
  },
  {
    id: 'project-4',
    slug: 'pathari-sanischare-hospital',
    title: '15 Bedded Pathari Sanischare Municipal Hospital',
    category: 'Healthcare',
    clientType: 'government',
    location: 'Morang',
    scope: 'Healthcare Facility',
    highlights: ['15 Beds', 'Municipal Hospital', 'Public Healthcare'],
    images: {
      thumbnail: '/images/projects/legacy/project-4.jpg',
      featured: '/images/projects/legacy/project-4.jpg',
      gallery: [],
    },
    seo: {
      title: 'Pathari Sanischare Municipal Hospital | KNS Projects',
      description: '15 bedded municipal hospital at Pathari Sanischare, Morang.',
    },
  },
  {
    id: 'project-5',
    slug: 'pathari-khola-bridge',
    title: 'Buddha Marga ko Pathari Khola ma Pul Nirman, Pathari, Morang',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Bridge Construction',
    highlights: ['Bridge Construction', 'Buddha Marga', 'Connectivity'],
    images: {
      thumbnail: '/images/projects/legacy/project-5.jpg',
      featured: '/images/projects/legacy/project-5.jpg',
      gallery: [],
    },
    seo: {
      title: 'Pathari Khola Bridge | KNS Projects',
      description: 'Bridge construction over Pathari Khola on Buddha Marga, Morang.',
    },
  },
  {
    id: 'project-6',
    slug: 'jahada-municipal-hospital',
    title: '15 Bedded Municipal Hospital at Jahada, Morang',
    category: 'Healthcare',
    clientType: 'government',
    location: 'Morang',
    scope: 'Healthcare Facility',
    status: 'running',
    completionPercentage: 90,
    contractValue: 'NPR 149.7M',
    highlights: ['15 Beds', 'Municipal Hospital', 'Rural Healthcare'],
    images: {
      thumbnail: '/images/projects/legacy/project-6.jpg',
      featured: '/images/projects/legacy/project-6.jpg',
      gallery: [],
    },
    seo: {
      title: 'Jahada Municipal Hospital | KNS Projects',
      description: '15 bedded municipal hospital at Jahada, Morang.',
    },
  },
  {
    id: 'project-7',
    slug: 'jahada-administration-building',
    title: 'Administration Building at Jahada-5, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Morang',
    scope: 'Administrative Building',
    highlights: ['Government Office', 'Administrative Hub', 'Public Service'],
    images: {
      thumbnail: '/images/projects/legacy/project-7.jpg',
      featured: '/images/projects/legacy/project-7.jpg',
      gallery: [],
    },
    seo: {
      title: 'Jahada Administration Building | KNS Projects',
      description: 'Administration building at Jahada-5, Morang.',
    },
  },
  {
    id: 'project-8',
    slug: 'prime-minister-park-biratnagar',
    title: 'Prime Minister Park at Biratnagar, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Public Park',
    status: 'running',
    completionPercentage: 85,
    contractValue: 'NPR 150.6M',
    highlights: ['Public Park', 'Urban Development', 'Landmark Project'],
    images: {
      thumbnail: '/images/projects/legacy/project-8.jpg',
      featured: '/images/projects/legacy/project-8.jpg',
      gallery: [],
    },
    seo: {
      title: 'Prime Minister Park | KNS Projects',
      description: 'Prime Minister Park at Biratnagar, Morang.',
    },
  },
  {
    id: 'project-9',
    slug: 'patan-secondary-school',
    title: 'Patan Secondary School at Patandhoka in Lalitpur District',
    category: 'Educational',
    clientType: 'institutional',
    location: 'Lalitpur',
    scope: 'School Building',
    highlights: ['Secondary School', 'Educational Infrastructure', 'Lalitpur'],
    images: {
      thumbnail: '/images/projects/legacy/project-9.jpg',
      featured: '/images/projects/legacy/project-9.jpg',
      gallery: [],
    },
    seo: {
      title: 'Patan Secondary School | KNS Projects',
      description: 'Patan Secondary School at Patandhoka, Lalitpur District.',
    },
  },
  {
    id: 'project-10',
    slug: 'admin-building-kavrepalanchowk',
    title: 'Administrative Building and Land Development, Kavrepalanchowk',
    category: 'Government',
    clientType: 'government',
    location: 'Kavrepalanchowk',
    scope: 'Administrative Building',
    highlights: ['Admin Building', 'Land Development', 'Government'],
    images: {
      thumbnail: '/images/projects/legacy/project-10.jpg',
      featured: '/images/projects/legacy/project-10.jpg',
      gallery: [],
    },
    seo: {
      title: 'Administrative Building Kavrepalanchowk | KNS Projects',
      description: 'Administrative building and land development in Kavrepalanchowk.',
    },
  },
  {
    id: 'project-12',
    slug: 'mangadh-water-supply-biratnagar',
    title: 'Mangadh Sahalagani Water Supply and Sanitation Project, Biratnagar, Morang',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Water Supply & Sanitation',
    highlights: ['Water Supply', 'Sanitation', 'Community Project'],
    images: {
      thumbnail: '/images/projects/legacy/project-12.jpg',
      featured: '/images/projects/legacy/project-12.jpg',
      gallery: [],
    },
    seo: {
      title: 'Mangadh Water Supply Project | KNS Projects',
      description: 'Water supply and sanitation project in Biratnagar, Morang.',
    },
  },
  {
    id: 'project-13',
    slug: 'kiratichowk-birendranagar-road',
    title: 'Kiratichowk Birendranagar Road, Pathari Sanischare Municipality',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Road Construction',
    highlights: ['Road Construction', 'Municipal Road', 'Connectivity'],
    images: {
      thumbnail: '/images/projects/legacy/project-13.jpg',
      featured: '/images/projects/legacy/project-13.jpg',
      gallery: [],
    },
    seo: {
      title: 'Kiratichowk Birendranagar Road | KNS Projects',
      description: 'Road construction at Pathari Sanischare Municipality, Morang.',
    },
  },
  {
    id: 'project-14',
    slug: 'stormwater-concrete-drain',
    title: 'Stormwater Concrete Drain',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Drainage System',
    highlights: ['Stormwater Drain', 'Concrete Construction', 'Urban Infrastructure'],
    images: {
      thumbnail: '/images/projects/legacy/project-14.jpg',
      featured: '/images/projects/legacy/project-14.jpg',
      gallery: [],
    },
    seo: {
      title: 'Stormwater Concrete Drain | KNS Projects',
      description: 'Stormwater concrete drain construction project.',
    },
  },
  {
    id: 'project-16',
    slug: 'gorkha-patra-sansthan-building',
    title: 'Gorkha Patra Sansthan Building',
    category: 'Commercial',
    clientType: 'commercial',
    location: 'Biratnagar',
    scope: 'Commercial Building',
    highlights: ['Media House', 'Commercial Building', 'Institutional'],
    images: {
      thumbnail: '/images/projects/legacy/project-16.jpg',
      featured: '/images/projects/legacy/project-16.jpg',
      gallery: [],
    },
    seo: {
      title: 'Gorkha Patra Sansthan Building | KNS Projects',
      description: 'Gorkha Patra Sansthan commercial building construction.',
    },
  },
  {
    id: 'project-17',
    slug: 'aarohan-gurukul-biratnagar',
    title: 'Theater Complex cum Residential School for Aarohan Gurukul, Biratnagar, Morang',
    category: 'Commercial',
    clientType: 'commercial',
    location: 'Biratnagar',
    scope: 'Theater & School Complex',
    highlights: ['Theater Complex', 'Residential School', 'Cultural Hub'],
    images: {
      thumbnail: '/images/projects/legacy/project-17.jpg',
      featured: '/images/projects/legacy/project-17.jpg',
      gallery: [],
    },
    seo: {
      title: 'Aarohan Gurukul Complex | KNS Projects',
      description: 'Theater complex and residential school for Aarohan Gurukul in Biratnagar.',
    },
  },
  {
    id: 'project-19',
    slug: 'civil-engineering-department-building',
    title: 'Department of Civil Engineering Building',
    category: 'Government',
    clientType: 'government',
    location: 'Morang',
    scope: 'Government Building',
    highlights: ['Engineering Department', 'Government Office', 'Institutional'],
    images: {
      thumbnail: '/images/projects/legacy/project-19.jpg',
      featured: '/images/projects/legacy/project-19.jpg',
      gallery: [],
    },
    seo: {
      title: 'Civil Engineering Department Building | KNS Projects',
      description: 'Department of Civil Engineering building construction.',
    },
  },
  {
    id: 'project-20',
    slug: 'paramedical-building-budhiganga',
    title: 'Paramedical Building, Budhiganga-4, Morang',
    category: 'Commercial',
    clientType: 'commercial',
    location: 'Morang',
    scope: 'Medical Building',
    highlights: ['Paramedical Facility', 'Healthcare Infrastructure', 'Commercial'],
    images: {
      thumbnail: '/images/projects/legacy/project-20.jpg',
      featured: '/images/projects/legacy/project-20.jpg',
      gallery: [],
    },
    seo: {
      title: 'Paramedical Building | KNS Projects',
      description: 'Paramedical building at Budhiganga-4, Morang.',
    },
  },
  {
    id: 'project-21',
    slug: 'district-treasury-office-biratnagar',
    title: 'District Treasury Controller (Ko. Le. Ni. Ka.) Office Building, Biratnagar, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Government Office',
    highlights: ['Treasury Office', 'Government Building', 'Administrative'],
    images: {
      thumbnail: '/images/projects/legacy/project-21.jpg',
      featured: '/images/projects/legacy/project-21.jpg',
      gallery: [],
    },
    seo: {
      title: 'District Treasury Controller Office | KNS Projects',
      description: 'District Treasury Controller office building in Biratnagar, Morang.',
    },
  },
  {
    id: 'project-22',
    slug: 'karmachari-sanchaya-kosh-office',
    title: 'Office Building of Karmachari Sanchaya Kosh',
    category: 'Government',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Government Office',
    highlights: ['Provident Fund Office', 'Government Building', 'Financial Institution'],
    images: {
      thumbnail: '/images/projects/legacy/project-22.jpg',
      featured: '/images/projects/legacy/project-22.jpg',
      gallery: [],
    },
    seo: {
      title: 'Karmachari Sanchaya Kosh Office | KNS Projects',
      description: 'Office building of Karmachari Sanchaya Kosh.',
    },
  },
  {
    id: 'project-23',
    slug: 'district-administration-office-biratnagar',
    title: 'District Administration Office, Biratnagar, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Government Office',
    highlights: ['District Admin Office', 'Government Hub', 'Public Service'],
    images: {
      thumbnail: '/images/projects/legacy/project-23.jpg',
      featured: '/images/projects/legacy/project-23.jpg',
      gallery: [],
    },
    seo: {
      title: 'District Administration Office | KNS Projects',
      description: 'District Administration Office in Biratnagar, Morang.',
    },
  },
  {
    id: 'project-25',
    slug: 'urban-development-office-biratnagar',
    title: 'Office Building of Urban Development & Building Construction, Biratnagar, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Government Office',
    highlights: ['Urban Development', 'Building Construction Dept', 'Government'],
    images: {
      thumbnail: '/images/projects/legacy/project-25.jpg',
      featured: '/images/projects/legacy/project-25.jpg',
      gallery: [],
    },
    seo: {
      title: 'Urban Development Office | KNS Projects',
      description: 'Office of Urban Development & Building Construction in Biratnagar.',
    },
  },
  {
    id: 'project-26',
    slug: 'jamc-academic-block-biratnagar',
    title: 'Academic Block of Janta Aadarsha Multiple Campus (JAMC), PU, Biratnagar, Morang',
    category: 'Educational',
    clientType: 'institutional',
    location: 'Biratnagar',
    scope: 'Academic Building',
    highlights: ['Academic Block', 'University Campus', 'Educational'],
    images: {
      thumbnail: '/images/projects/legacy/project-26.jpg',
      featured: '/images/projects/legacy/project-26.jpg',
      gallery: [],
    },
    seo: {
      title: 'JAMC Academic Block | KNS Projects',
      description: 'Academic block of Janta Aadarsha Multiple Campus in Biratnagar.',
    },
  },
  {
    id: 'project-27',
    slug: 'staff-quarter-inaruwa-substation',
    title: 'Staff Quarter at Inaruwa Substation, Inaruwa, Sunsari',
    category: 'Government',
    clientType: 'government',
    location: 'Sunsari',
    scope: 'Staff Quarters',
    highlights: ['Staff Quarter', 'Power Substation', 'Government Housing'],
    images: {
      thumbnail: '/images/projects/legacy/project-27.jpg',
      featured: '/images/projects/legacy/project-27.jpg',
      gallery: [],
    },
    seo: {
      title: 'Inaruwa Substation Staff Quarter | KNS Projects',
      description: 'Staff quarter at Inaruwa substation in Sunsari.',
    },
  },
  {
    id: 'project-31',
    slug: 'rcc-overhead-tank',
    title: '450 Cum Capacity RCC Overhead Tank',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Water Infrastructure',
    highlights: ['450 Cum Capacity', 'RCC Construction', 'Water Storage'],
    images: {
      thumbnail: '/images/projects/legacy/project-31.jpg',
      featured: '/images/projects/legacy/project-31.jpg',
      gallery: [],
    },
    seo: {
      title: '450 Cum RCC Overhead Tank | KNS Projects',
      description: '450 cum capacity RCC overhead tank construction.',
    },
  },

  // ── New projects from General Construction Experience PDF ──

  {
    id: 'project-34',
    slug: 'rcc-bridge-simariya-road',
    title: 'RCC Bridge Construction, Simariya Road, Morang',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Bridge Construction',
    status: 'completed',
    year: '2009',
    highlights: ['RCC Bridge', 'Simariya Road', 'Sunsari-Morang Bridge Project'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'RCC Bridge Simariya Road | KNS Projects',
      description: 'RCC bridge construction on Simariya Road, Morang.',
    },
  },
  {
    id: 'project-35',
    slug: 'rcc-overhead-tank-mangsuwa',
    title: '450m³ RCC Overhead Water Tank, Mangsuwa',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Water Infrastructure',
    status: 'completed',
    year: '2009',
    highlights: ['450m³ Capacity', 'RCC Construction', 'Water Supply'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: '450m³ RCC Overhead Tank Mangsuwa | KNS Projects',
      description: '450m³ RCC overhead water tank construction in Mangsuwa, Morang.',
    },
  },
  {
    id: 'project-36',
    slug: 'dormitory-lutheran-world-federation',
    title: '3-Storeys Dormitory Building, Lutheran World Federation, Kathmandu',
    category: 'Commercial',
    clientType: 'institutional',
    location: 'Kathmandu',
    scope: 'Dormitory Building',
    status: 'completed',
    year: '2006',
    highlights: ['3-Storey Building', 'Dormitory Facility', 'International Organization'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Dormitory Building Lutheran World Federation | KNS Projects',
      description: '3-storey dormitory building for Lutheran World Federation, Kathmandu.',
    },
  },
  {
    id: 'project-37',
    slug: 'warehouse-district-election-office',
    title: 'Ware House Construction, District Election Office, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Morang',
    scope: 'Warehouse Construction',
    status: 'completed',
    year: '2008',
    highlights: ['Warehouse Facility', 'Government Storage', 'Election Office'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Warehouse District Election Office | KNS Projects',
      description: 'Warehouse construction for District Election Office, Morang.',
    },
  },
  {
    id: 'project-38',
    slug: 'compound-wall-ard-usaid',
    title: 'Compound Wall, Buildings, Slab Culvert & Garage for ARD/USAID/NGCPP-Nepal',
    category: 'Government',
    clientType: 'government',
    location: 'Morang',
    scope: 'Infrastructure & Buildings',
    status: 'completed',
    year: '2010',
    highlights: ['Compound Wall', 'Slab Culvert', 'International Development Project'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'ARD/USAID/NGCPP Infrastructure | KNS Projects',
      description: 'Compound wall, buildings, slab culvert and garage for ARD/USAID/NGCPP-Nepal.',
    },
  },
  {
    id: 'project-39',
    slug: 'warehouse-district-admin-sunsari',
    title: 'Ware House & Infrastructures, District Admin Office, Sunsari',
    category: 'Government',
    clientType: 'government',
    location: 'Sunsari',
    scope: 'Warehouse & Infrastructure',
    status: 'completed',
    year: '2011',
    highlights: ['Warehouse', 'Compound Wall', 'Government Infrastructure'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Warehouse District Admin Office Sunsari | KNS Projects',
      description: 'Warehouse and infrastructure at District Admin Office, Sunsari.',
    },
  },
  {
    id: 'project-40',
    slug: 'child-correction-home-morang',
    title: 'Child Correction Home, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Morang',
    scope: 'Institutional Building',
    status: 'completed',
    year: '2009',
    highlights: ['Child Welfare Facility', 'Government Institution', 'Social Infrastructure'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Child Correction Home | KNS Projects',
      description: 'Child correction home construction in Morang.',
    },
  },
  {
    id: 'project-41',
    slug: 'pakali-mahendra-nagar-chatra-road',
    title: 'Pakali-Mahendra Nagar-Chatra Road Sub-Project',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Sunsari',
    scope: 'Road Construction',
    status: 'completed',
    year: '2010',
    highlights: ['Road Sub-Project', 'RRRSDP', 'Rural Road Network'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Pakali-Mahendra Nagar Road | KNS Projects',
      description: 'Pakali-Mahendra Nagar-Chatra road sub-project in Sunsari.',
    },
  },
  {
    id: 'project-42',
    slug: 'office-ministry-agriculture-morang',
    title: 'Office Building, Ministry of Agriculture & Co-operative, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Morang',
    scope: 'Government Office',
    status: 'completed',
    year: '2012',
    highlights: ['Ministry Office', 'Co-operative Department', 'Government Building'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Ministry of Agriculture Office | KNS Projects',
      description: 'Office building for Ministry of Agriculture & Co-operative, Morang.',
    },
  },
  {
    id: 'project-43',
    slug: 'innaruwa-duhabi-ithari-dharan-corridor',
    title: 'Infrastructure Development, Innaruwa-Duhabi-Ithari-Dharan Corridor',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Infrastructure Development',
    status: 'completed',
    year: '2012',
    highlights: ['Urban Corridor', 'DUDBC Project', 'Multi-city Infrastructure'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Innaruwa-Duhabi-Ithari-Dharan Corridor | KNS Projects',
      description: 'Infrastructure development along Innaruwa-Duhabi-Ithari-Dharan corridor.',
    },
  },
  {
    id: 'project-44',
    slug: 'nepal-telecom-exchange-building',
    title: 'Exchange Building, Nepal Telecom, Biratnagar',
    category: 'Commercial',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Commercial Building',
    status: 'completed',
    year: '2013',
    highlights: ['Telecom Exchange', 'Nepal Telecom', 'Eastern Regional Directorate'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Nepal Telecom Exchange Building | KNS Projects',
      description: 'Exchange building for Nepal Telecom at Roadsesh, Biratnagar.',
    },
  },
  {
    id: 'project-45',
    slug: 'canal-structures-eastern-irrigation',
    title: 'Canal and Structures, Eastern Irrigation Development Division, Sunsari',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Sunsari',
    scope: 'Irrigation',
    status: 'completed',
    year: '2013',
    highlights: ['Canal Construction', 'Irrigation Structures', 'Eastern Region'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Canal & Structures Eastern Irrigation | KNS Projects',
      description: 'Canal and structures for Eastern Irrigation Development Division, Sunsari.',
    },
  },
  {
    id: 'project-46',
    slug: 'desilting-cmc-chatra-main-canal',
    title: 'Desilting Works of CMC, Chatra Main Canal',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Canal Maintenance',
    status: 'completed',
    year: '2014',
    highlights: ['Desilting Works', 'Chatra Main Canal', 'Sunsari-Morang Irrigation'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Desilting Chatra Main Canal | KNS Projects',
      description: 'Desilting works of CMC, Chatra Main Canal, Biratnagar.',
    },
  },
  {
    id: 'project-47',
    slug: 'cottage-small-industry-office',
    title: 'Cottage & Small Industry Office Building, Biratnagar',
    category: 'Government',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Government Office',
    status: 'completed',
    year: '2014',
    highlights: ['Industry Office', 'Government Building', 'Biratnagar'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Cottage & Small Industry Office | KNS Projects',
      description: 'Cottage & Small Industry Office building construction, Biratnagar.',
    },
  },
  {
    id: 'project-48',
    slug: 'kocheni-khola-rcc-bridge',
    title: 'Kocheni Khola RCC Girder Bridge, Biratnagar',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Bridge Construction',
    status: 'completed',
    year: '2014',
    highlights: ['RCC Girder Bridge', 'Kocheni Khola', 'District Development'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Kocheni Khola RCC Bridge | KNS Projects',
      description: 'Kocheni Khola RCC girder bridge construction in Biratnagar.',
    },
  },
  {
    id: 'project-49',
    slug: 'rcc-overhead-tank-225cum',
    title: 'RCC Overhead Water Storage Tank (225 CUm), Morang',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Water Infrastructure',
    status: 'completed',
    year: '2015',
    highlights: ['225 CUm Capacity', 'Overhead Tank', 'Water Storage'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'RCC Overhead Tank 225 CUm | KNS Projects',
      description: 'RCC overhead water storage tank (225 CUm) construction in Morang.',
    },
  },
  {
    id: 'project-50',
    slug: 'helipad-biratnagar-airport',
    title: 'Helipad at Biratnagar Airport',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Biratnagar',
    scope: 'Aviation Infrastructure',
    status: 'completed',
    year: '2015',
    highlights: ['Helipad Construction', 'Biratnagar Airport', 'Civil Aviation'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Helipad Biratnagar Airport | KNS Projects',
      description: 'Helipad construction at Biratnagar Airport.',
    },
  },
  {
    id: 'project-51',
    slug: 'blacktopped-road-jhapa-morang',
    title: 'Blacktopped Road Construction Works, Jhapa-Morang',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Morang',
    scope: 'Road Construction',
    status: 'completed',
    year: '2015',
    highlights: ['Blacktopped Road', 'Drainage Structures', 'Multi-location'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Blacktopped Road Jhapa-Morang | KNS Projects',
      description: 'Blacktopped road construction works including drainage structures in Jhapa-Morang.',
    },
  },
  {
    id: 'project-52',
    slug: 'water-tank-simara-sez',
    title: 'Overhead Water Tank and Deep Tube Well, Simara SEZ',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Kathmandu',
    scope: 'Water Infrastructure',
    status: 'completed',
    year: '2018',
    highlights: ['Overhead Water Tank', 'Deep Tube Well', 'Special Economic Zone'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Water Tank Simara SEZ | KNS Projects',
      description: 'Overhead water tank and deep tube well at Simara Special Economic Zone.',
    },
  },
  {
    id: 'project-53',
    slug: 'warehouse-nepal-red-cross-itahari',
    title: 'Warehouse & Boundary Wall, Nepal Red Cross Society, Itahari',
    category: 'Commercial',
    clientType: 'institutional',
    location: 'Sunsari',
    scope: 'Warehouse & Infrastructure',
    status: 'completed',
    year: '2019',
    highlights: ['Warehouse', 'Boundary Wall', 'Nepal Red Cross Society'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Nepal Red Cross Warehouse Itahari | KNS Projects',
      description: 'Warehouse and boundary wall for Nepal Red Cross Society at Itahari, Sunsari.',
    },
  },
  {
    id: 'project-54',
    slug: 'staff-quarter-nea-india-transmission',
    title: 'Staff Quarter, Store & Guard House, NEA Nepal-India Electricity Transmission',
    category: 'Government',
    clientType: 'government',
    location: 'Sunsari',
    scope: 'Staff Quarters',
    status: 'completed',
    year: '2019',
    highlights: ['NEA Transmission Project', 'Nepal-India Electricity', 'Staff Quarter & Store'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'NEA Nepal-India Transmission Staff Quarter | KNS Projects',
      description: 'Staff quarter, store and guard house for NEA Nepal-India Electricity Transmission project.',
    },
  },
  {
    id: 'project-55',
    slug: 'office-infrastructures-district-admin-morang',
    title: 'Office Building & Infrastructures, District Admin Office, Morang',
    category: 'Government',
    clientType: 'government',
    location: 'Morang',
    scope: 'Government Office',
    status: 'completed',
    year: '2011',
    highlights: ['Office Building', 'Government Infrastructure', 'District Administration'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'District Admin Office Morang | KNS Projects',
      description: 'Office building and infrastructures at District Admin Office, Morang.',
    },
  },
  {
    id: 'project-56',
    slug: 'timai-shantinagar-water-supply-jhapa',
    title: 'Timai Shantinagar Integrated Water Supply Project, Buddhashanti Municipality, Jhapa',
    category: 'Infrastructure',
    clientType: 'government',
    location: 'Jhapa',
    scope: 'Water Supply',
    status: 'running',
    completionPercentage: 90,
    contractValue: 'NPR 114.9M',
    highlights: ['Integrated Water Supply', 'Multi-ward Coverage', 'Federal Project'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'Timai Shantinagar Water Supply | KNS Projects',
      description: 'Integrated water supply project at Buddhashanti Municipality, Jhapa.',
    },
  },
  {
    id: 'project-57',
    slug: 'mch-block-purbanchal-university-morang',
    title: 'Ground Floor of MCH Block at Purbanchal University, Gothgaun, Morang',
    category: 'Healthcare',
    clientType: 'institutional',
    location: 'Morang',
    scope: 'Healthcare Facility',
    status: 'running',
    completionPercentage: 20,
    contractValue: 'NPR 120.5M',
    highlights: ['MCH Block', 'Purbanchal University', 'Healthcare Infrastructure'],
    images: {
      thumbnail: '/images/projects/placeholder.jpg',
      featured: '/images/projects/placeholder.jpg',
      gallery: [],
    },
    seo: {
      title: 'MCH Block Purbanchal University | KNS Projects',
      description: 'Ground floor MCH block at Purbanchal University, Gothgaun, Morang.',
    },
  },
];

/** All unique project categories */
export const projectCategories = [
  'Commercial',
  'Educational',
  'Government',
  'Healthcare',
  'Infrastructure',
];
